apiVersion: apps/v1
kind: Pod
metadata:
  name: dns-notification-oc
spec:
  selector:
    app: notification
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 8.8.8.8
    options:
      - name: ndots
        value: "5"
      #- name: edns0