#Deploy the service
apiVersion: v1
kind: Service
metadata:
  name: statement-service
  labels:
    app: statement
    solution: stock-trader
spec:
  type: NodePort 
  ports:
    - port: 8443
      nodePort: 31010
      targetPort: 8443
      name: https
  selector:
    app: statement
